name: ai_math_solver
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: any
  image_cropper: ^11.0.0
  camera: any
  gal: any
  gap: any
  external_path: any
  media_scanner: any
  google_generative_ai: ^0.4.7
  genai: ^0.0.1
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.20
  sqflite: ^2.3.3
  speech_to_text: ^7.3.0
  path: any
  flutter_tts: ^4.2.3
  path_provider: ^2.1.2
  flutter_markdown: ^0.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/




